### ISSUE TITLE
Search Engine Add isn't mandatory for Search Engine Remove

### ISSUE THREAD

**Issue by JasonNVSD** [cadeyrn/enterprise-policy-generator#117]
**Describe the bug**
When enabling "Modifies the list of search engines built into Firefox", the name and URL fields for "Add search engine(s)" become mandatory.  These shouldn't be mandatory when using the "Remove search engine(s)" fields.

**Version information:**
 - Firefox ESR 68.2.0
 - Enterprise Policy Generator 5.0.0

**Comment by cadeyrn** [comment]
Thanks for using Enterprise Policy Generator and for the report.

The fields marked as mandatory in the "Add search engine(s)" are already not mandatory for the "Remove search engine(s)" section. You can leave these fields empty and you will see that the "Remove search engine(s)" part still works.

I'll close this issue because everything is working but I am open for suggestions how to improve the UI/UX.
