### ISSUE TITLE
incorrect macOS directory specified in user interface

### ISSUE THREAD

**Issue by f-u-c-k-github** [cadeyrn/enterprise-policy-generator#210]
**Describe the bug**
The Enterprise Policy Generator user interface says the macOS user should create directory "distribution" in the directory "Firefox.app/Contents/Resources/".  This is not incorrect because the directory "Firefox.app" does not seem to exist anywhere in my directory structure.  It might be helpful if this instruction would tell me where the "Firefox.app" directory should be located relative to root, or relative to some other standard reference point.

**To Reproduce**
1. From the Firefox application, open the user interface for managing the Enterprise Policy Generator extension.
2. Read the instructions titled "Usage" on the right side of the window.
3. The incorrect instructions are located in the "Usage" section titled "Apple macOS:"

**Expected behavior**
I expected a correct description of where the referenced directory is located.

**Screenshots**
not needed

**Version information:**
 - Firefox version: 112.0.2 (64-bit)
 - Enterprise Policy Generator version 5.1.0

**Comment by elliotsmith** [comment]
correction:  in the above comments, the phrase "not incorrect" should read "not correct".  Thank you!

**Comment by elliotsmith** [comment]
Thanks for your fast reply, and thanks for the explanation!  

Until now I did not know anything about the special MacOS directories with the ".app" suffix.  This is why I did not guess that I need to search for more information about how to open a MacOS application package.

I understand explaining the OS is outside of your scope.  However, it can be very helpful for users if you can format your instructions so that you do not refer to the Firefox.app directory as if it is a normal directory.  Instead, if your instructions can call it with the name "Firefox application package", then this will allow the user with some "technical" capability to understand that this directory is special and different.  Any user who does not already know how to open the package can easily find the answer in a web search engine.

This is my suggestion for how to change the instructions:

Apple macOS: create a "distribution" directory inside the /Contents/Resources/ directory inside the Firefox application package and place the file “policies.json” there.

You could also change the instructions as follows, but maybe this is not a good idea, because this makes it very easy for the non-technical user to open the Firefox.app directory, and maybe the non-technical user will break things:

Apple macOS: create a directory called “distribution” in Firefox.app/Contents/Resources/ and place the file “policies.json” there. (To open the Firefox.app directory, right-click on the Firefox application and choose "show package contents" from the context menu)

Thanks for this great tool! : - )

**Comment by cadeyrn** [comment]
> Apple macOS: create a "distribution" directory inside the /Contents/Resources/ directory inside the Firefox application package and place the file “policies.json” there.

> Apple macOS: create a directory called “distribution” in Firefox.app/Contents/Resources/ and place the file “policies.json” there. ()

Thank you for your suggestions. I think such a text change would work for me since the text length still seems okay. I would probably choose a combination of both suggestions because the .app suffix is probably unknown for many users and with the context menu hint it's not that important. I like it to call it Firefox application package. So maybe something like this:

> Apple macOS: create a "distribution" directory inside the /Contents/Resources/ directory of the Firefox application package and place the file “policies.json” there. To open the application package, right-click on the Firefox application in the Finder and choose "show package contents" from the context menu.

So let's reopen this issue so that it can be considered for the next (and long overdue) update.
