### ISSUE TITLE
Import existing .json file

### ISSUE THREAD

**Issue by MadPAM** [cadeyrn/enterprise-policy-generator#49]
We have an existing .json file that was created using a different tool (CCK2). Is it possible to import this into Enterprise Policy Generator?
I tried the import function but it didn't do anything. It didn't add a configuration to the list in "load configuration". But there was also no error message.
Thanks in advance

**Comment by cadeyrn** [comment]
Hi,

thank you for using the Enterprise Policy Generator.

I don't know the .json file generated by CCK2. Does the CCK2 generate a policies.json file for Firefox 60+ or does the .json file contain something different? Could you please attach an example file from CCK2?

Anyway, You can't import an existing .json file into the Enterprise Policy Generator because the .json file does not conain any information about the interface of Enterprise Policy Generator. That's why the Enterprise Policy Generator has a own file format for configuration exports. The import feature of Enterprise Policy Generator only supports the own file format with all the information needed by the add-on.

I guess I should add an error message for invalid files, so I will track this work in this ticket.

**Comment by MadPAM** [comment]
I suspected as much. But was hoping that it would work...too bad. I have attached our .json so you can take a look.
[our.cck2.config.json.zip](https://github.com/cadeyrn/enterprise-policy-generator/files/2447070/our.cck2.config.json.zip)

**Comment by cadeyrn** [comment]
Thank you for sharing the file. As expected this .json file is something different and has nothing to do with the Enterprise Policies of Firefox 60+ and the Enterprise Policy Generator.

**Comment by cadeyrn** [comment]
The upload field is already restricted to .policy files and does not accept .json files. So there is nothing to do.
